version: '3.4'
services:
  gate:
    image: kkucht/rsww_184543_gate:latest
    depends_on:
        - rabbitmq 
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 140s
    ports:
         - 55278:80 
    environment:
        ASPNETCORE_ENVIRONMENT: Development
    networks:
        - rsww-184543-network
         

  hotelcommand:
    image: kkucht/rsww_184543_hotelcommand:latest
    depends_on:
        - rabbitmq 
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 140s
    ports:
         - 8020:80 
    networks:
        - rsww-184543-network
        - rsww-184543-postgres-net

  hotelquery:
    image: kkucht/rsww_184543_hotelquery:latest
    depends_on:
        - rabbitmq 
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 140s
    ports:
         - 8030:80 
    networks:
        - rsww-184543-network
        - rsww-184543-mongo-net

  login:
    image: kkucht/rsww_184543_login:latest
    depends_on:
        - rabbitmq 
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 140s
    ports:
         - 8040:80 
    networks:
        - rsww-184543-network
        - rsww-184543-mongo-net


  offercommand:
    image: kkucht/rsww_184543_offercommand:latest
    depends_on:
        - rabbitmq 
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 140s
    ports:
         - 8050:80 
    networks:
        - rsww-184543-network
        - rsww-184543-postgres-net

  offerquery:
    image: kkucht/rsww_184543_offerquery:latest
    depends_on:
        - rabbitmq 
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 140s
    ports:
         - 8060:80 
    networks:
        - rsww-184543-network
        - rsww-184543-mongo-net

  payment:
    image: kkucht/rsww_184543_payment:latest
    depends_on:
        - rabbitmq 
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 140s
    ports:
         - 8070:80 
    networks:
        - rsww-184543-network
        - rsww-184543-mongo-net

  transportcommand:
    image: kkucht/rsww_184543_transportcommand:latest
    depends_on:
        - rabbitmq 
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 140s
    ports:
         - 8090:80 
    networks:
        - rsww-184543-network
        - rsww-184543-postgres-net

  transportquery:
    image: kkucht/rsww_184543_transportquery:latest
    depends_on:
        - rabbitmq 
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 140s
    ports:
         - 8100:80 
    networks:
        - rsww-184543-network
        - rsww-184543-mongo-net

  trip:
    image: kkucht/rsww_184543_trip:latest
    depends_on:
        - rabbitmq 
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 140s
    ports:
         - 8110:80 
    networks:
        - rsww-184543-network
          
  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:latest 
    hostname: 'rabbitmq'
    container_name: 'rabbitmq'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 140s
    ports: 
        - 5672:5672  
        - 15672:15672 
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
    networks:
        - rsww-184543-network

  front:
    image: kkucht/rsww_184543_front:latest
    hostname: 'front'
    container_name: 'front'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 140s
    ports:
      - 18454:80

networks:
  rsww-184543-network:
    driver: bridge
  rsww-184543-mongo-net:
    external: true
    name: admin-mongodb_default
  rsww-184543-postgres-net:
    external: true
    name: admin-postgres_default


volumes:
  postgres_data: