DROP USER IF EXISTS transport;
CREATE USER transport WITH PASSWORD 'transport';
DROP DATABASE IF EXISTS transport;
CREATE DATABASE transport;
GRANT ALL PRIVILEGES ON DATABASE transport to transport;

DROP USER IF EXISTS offer;
CREATE USER offer WITH PASSWORD 'offer';
DROP DATABASE IF EXISTS offer;
CREATE DATABASE offer;
GRANT ALL PRIVILEGES ON DATABASE offer to offer;

DROP USER IF EXISTS hotel;
CREATE USER hotel WITH PASSWORD 'hotel';
DROP DATABASE IF EXISTS hotel;
CREATE DATABASE hotel;
GRANT ALL PRIVILEGES ON DATABASE hotel to hotel;